# This class can be used to create random deck names
class_name DeckNameRandomizer
extends Reference


var adverbs = [
	"Totally", "Mostly", "Regularly", "Just", "Too", "Very", "Never",
	"Seldom", "Rather", "Still", "Almost",
]

var adjectives = [
	"Awesome", "Brilliant", "New", "Newer", "Newest", "Stable",
	"Solid", "Janky", "Jankiest", "Questionable", "Curious", "Weird",
	"Broken", "Overpowered", "Fun", "Fast", "Ephemeral", "Sensual",
	"Cautious", "Scientific", "Explosive", "Poisonous", "Humorous",
	"Green", "Crimson", "Yellow", "Black", "White", "Terracota", "Blue", "Grey",
	"Holy", "Unholy", "Mighty", "Weak", "Boring", "Swimming", "Drowning",
	"Ridiculous", "Embarasing", "Discombobulating", "Routing", "Boring",
	"Working", "Failing", "Ugly", "Bad", "Good", "Horrible", "Terrible",
	"Catalytic", "Mind-blowing", "Cute", "Slow", "Elaborate", "Cracked",
	"Cheesy", "Rich", "Poor", "Alchemical", "Squishy", "Lagging", "Stumbling",
	"Horny", "Wooden", "Polished", "Sharp", "Asynchronous", "Phasing",
	"Beholding", "Reasonable", "Absurd", "Irrational", "Logical", "Spineless",
	"Fragmented", "Sorry", "Freak", "Geeky", "Nuclear", "Radioactive",
	"Breaking", "Magic", "Quivering", "Fungal", "Rotting", "Phyrric",
	"Ethereal", "Astral", "Cold", "Hot", "Zodiac", "Proletarian",
	"Conjuring", "Rapid", "Rotating", "Searing", "Evil", "Thieving",
	"Fractal", "Grimdark", "Dank", "Desperate", "Aerodynamic", "Neutral",
	"Heretic", "Rugose", "Witching", "Bleeding", "Bald", "Wet", "Dry",
	"Androgynous", "Whining", "Foolproof", "Foolish", "Smoking", "Parasitic",
	"Drunk", "Fermented", "Undead", "Underwater", "Epicurian", "Mad", "Sane",
	"Hyperactive", "Ghostly", "Grim", "Repeating", "Recycled", "Growing", "Sick",
	"Gentle", "Guiding", "Ascending", "Calm", "Stumbling", "Crying", "Infinite",
	"Petty", "Pretty", "Pointy", "Lovable", "Professional", "Juggling",
	"Cruel", "Gold", "Silver", "Sterile", "Stimulating", "Filthy", "Boneless",
	"Moldy", "Absorbing", "Grainy", "Fuzzy", "Lurking", "Old", "Oldest", "Ancient",
	"Righteous", "Trampling", "Flanking", "Forgotten", "Harsh", "Folded",
	"Military", "Industrial", "High", "Low", "Sad", "Emotional", "Depressed",
	"Psychotic", "Manic", "Bigoted", "Hated", "Theoretical", "Straight",
	"Crooked", "Brutal", "Stretching", "Controlling", "Juicy", "Thicc",
	"Arousing", "Pimpled", "Dotted", "Rebelious", "Dominating", "Giant",
	"Ravenous", "Native", "Invasive", "Invading", "Charging", "First",
	"Last", "Classic", "Hyper", "Honest", "Delicious", "Sonic", "Hilarious",
	"4D", "Homeless", "Lonely", "Popular", "Prismatic", "Furious", "Infamous",
	"Dodgy", "Curvaceous", "Spicy", "Retro", "Voracious", "Gilded",
]

var nouns = [
	"Deck", "Deck", "Deck", "Bible", "Weapon", "Jank", "Pattern",
	"Pile", "Array", "Garbage", "Book", "Disaster", "Destruction", "Victory",
	"Loss", "Shuffle", "Fatality", "Discovery", "Exploration", "God",
	"Monster", "Potato", "Zuccini", "Broccoli", "Demon", "Angel", "Beast",
	"Salad", "Knife", "Spork", "Soup", "Gazebo", "Pea", "Penis", "Rose",
	"Match", "Flower", "Bullet", "Pepper", "Clown", "Clone", "Joke", "Duck",
	"Foot", "Palm", "Cheese", "Monkey", "Gorilla", "Donkey", "Ninja", "Samurai",
	"Bank", "Bull", "Corner", "Dollar", "Credit", "Pogo", "Music", "Melody",
	"Souffle", "Meat", "Blitz", "Chemistry", "Pling", "Ping", "Link", "Catastrophy",
	"Butt", "Tooth", "Eyeball", "Brain", "Erection", "Stairway", "Song", "Whale",
	"Doplhin", "Shark", "Octopus", "Amoeba", "Proton", "Zealot", "Neutron", "Atom",
	"Pie", "Pi", "Radius", "Circle", "Cake", "Dam", "Wave", "Sailor", "Spell",
	"Source", "Mushroom", "Pulse", "Pus", "Andromeda", "Galaxy", "Doctor",
	"Star", "Nebula", "Hole", "Sun", "Rock", "Meteor", "Zenith", "leader",
	"Grasshopper", "Cockroach", "Mouse", "Bug", "Wasp", "Laser", "Beam", "Crystal",
	"Sword", "Bow", "Hammer", "Axe", "Spear", "Shield", "Overlord", "Warlord",
	"King", "Champion", "Hero", "Peasant", "Scum", "Bucket", "Descent", "Cult",
	"Focus", "Punch", "Lotus", "Kiss", "Blizzard", "Meditation", "Whip", "Sauce",
	"Surgery", "Impact", "Mace", "Assault", "Chivalry", "Melon", "Vampire",
	"Boomer", "Dictator", "Stronghold", "Emperor", "Forfeit", "Thingamajib",
	"Goober", "Stuff", "Engine", "Pirate", "Candle", "Lamp", "Djinn", "Ghoul",
	"Medal", "Spirit", "Servant", "Cave", "Despair", "Tumor", "Chain", "Vomit",
	"Energy", "Surprise", "Riff", "Rift", "Vision", "Pledge", "Miracle",
	"Risotto", "Robot", "Punk", "Bowl", "Hash", "Glasses", "Mucus", "Sonata",
	"Balet", "Exercise", "Pain", "Hex", "Diamond", "Gem", "Peanut", "Vortex",
	"Butterfly", "Snowflake", "Wisdom", "Tower", "Virus", "Ambrosia", "Colony",
	"Island", "Swamp", "Worm", "Maggots", "Printer", "Spawn", "Box", "Cartography",
	"Queen", "Sandal", "Choreography", "Survival", "School", "Kindergarten",
	"Frog Leg", "Hairball", "Swinger", "Trumpet", "Bunny", "Joystick",
	"Opossum", "Spray", "Battle", "Algae", "Lint", "Dust", "Dandruff", "Lice",
	"Feedback", "Noise", "Stampede", "Weeb", "Neck", "Katana", "Beard",
	"Godfather", "Bait", "Jail", "Paw", "Program", "Army", "Soldier", "Steam",
	"Fart", "Fedora", "Goth", "Man", "Woman", "Child", "Werewolf", "Fairy",
	"Nanny", "Crone", "Iron", "Maiden", "Virgin", "Current", "Voltage", "Power",
	"Moon", "Death", "Shackles", "Control", "Mouthfeel", "Blitz", "Jank", "Secret",
	"Police", "Authority", "Revolution", "Blood", "Anarchist", "Murder", "Bomb",
	"Boot", "Broth", "Mammoth", "Berserker", "Barbarian", "Omega", "Sanctions",
	"Chicken", "Piggy", "Chocolate", "Stick", "Membrane", "Mix", "Cell", "DNA",
	"Protein", "Medicine", "Venom", "Stalker", "Fanatic", "Dice", "Chips",
	"Chess", "Street", "Armadillo", "Armor", "Color", "Hook", "Rum", "Beaver",
	"River", "Bingo", "Jackpot", "House", "Dungeon", "Revenge", "Doge",
	"Cryptocurrency", "8bit", "Chiptune", "Synthwave", "Meatball", "Fog",
]

var appends = [
	"of Death", "of Madness", "of Steel", "of Ichor", "of Cards",
	"of Silence", "of Fire", "of Water", "of Air", "of Earth", "of Fruit",
	"of War", "of Peace", "of Sloth", "of Rage", "of Pride", "of Lust",
	"of Salt", "of Wat", "of Worth", "of Horror", "of Terror", "of Jokes",
	"of Marble", "of Wat", "of Cheese", "of Doom", "of Desire", "of Passion",
	"of the Cosmos", "of the Nether", "from the Wormhole", "out of Time",
	"of Heaven", "from Hell", "of Limbo", "from Tartarus", "of Charm", "of Lies",
	"of Annoyance", "of Sorcery", "of Flesh", "of Clarity", "of Ice", "of Lightning",
	"of the Serpent", "of Nothing", "of the People", "of the Master", "of the Noob",
	"of the Elements", "of Malice", "of the Underworld", "of Wonders", "of Sanity",
	"of the Void", "of Chaos", "of Order", "of the Elder Gods", "of Blasphemy",
	"that sucks", "that slaps", "that rocks", "with massive faults",
	"with bugs", "which never sleeps", "from the depths", "which should not be",
	"- alpha version", "on special offer", "from the future", "from the past",
	"from an alternate dimension", "with special needs", "and stuff",
	"which shall not be named", "of Justice", "with sprinkles",
	"with a cherry on top", "and a Bottle o' Rum", "of Hate", "of the Tides",
	"of the Wolf", "of Truth", "of the Four Winds", "of Darkness", "of Light",
	"of Glory", "that whistles ruefully"
]
