name: GUT

on:
  push:
    branches:
      - conversion

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  GUT:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Test
      uses: ceceppa/godot-gut-ci@main
      with:
        # required
        godot_version: "4.2"
        gut_params: -gdir=res://tests/
