name: GUT

on:
  push:
    branches:
      - conversion

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: croconut/godot-tester@v5
      with:
        # required
        version: "4.2.2"
        # the type of release of godot that the tests should be run with
        release_type: "rc2"
        # how long to spend importing assets before tests are run
        import-time: "10"
        # default is false, set true to count asserts instead of tests
        assert-check: "true" 
        # how long tests can run in seconds
        test-timeout: "900"
        # the ratio of tests that must pass for this action to pass
        # e.g. 0.6 means 60% of your tests must pass
        minimum-pass: "0.70"
        # the directory containing Gut tests
        test-dir: "res://tests"
        # Directory containing Gut tests
        direct-scene: "tests/cli/tests.tscn"
        # relative path to the xml file to read / write GUT's results from, recommended
        # for direct-scene users to check this file if you have issues
        result-output-file: "test_results.xml"

