name: GUT

on:
  push:
    branches-ignore:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GUT_Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Check out personal godot-tester repository
        uses: actions/checkout@v3
        with:
          repository: db0/godot-tester
          path: ./.github/actions/godot-tester
      # Runs a single command using the runners shell
      - name: Godot Tester
        uses: ./.github/actions/godot-tester
        with:
          version: 3.4.4
          # should be long enough for asset import files to get generated
          import-time: 10
          assert-check: true
          max-fails: 0
          # How long the test should be run before it's timed out and fails
          test-timeout: 900
          # Directory containing Gut tests
          direct-scene: tests/cli/tests.tscn